### ISSUE TITLE
No module named 'gymnasium.vector.utils.spaces

### ISSUE THREAD

**Issue by lidaken** [ScheiklP/movement-primitive-diffusion#4]
Hello, when I complete the installation step by step, and I try to run the " python scripts/train.py --config-name dummy +experiments/obstacle_avoidance=train_prodmp_transformer". But I got error, and I can't find the solution. Can you give the gymnasium's version or solve this error? Thanks a lot.
`Traceback (most recent call last):
  File "/home/lxc/movement-primitive-diffusion/scripts/train.py", line 14, in <module>
    from movement_primitive_diffusion.utils.setup_helper import setup_train, setup_wandb_metrics, get_group_from_override
  File "/home/lxc/movement-primitive-diffusion/movement_primitive_diffusion/utils/setup_helper.py", line 17, in <module>
    from movement_primitive_diffusion.workspaces.base_vector_workspace import BaseVectorWorkspace
  File "/home/lxc/movement-primitive-diffusion/movement_primitive_diffusion/workspaces/base_vector_workspace.py", line 16, in <module>
    from movement_primitive_diffusion.utils.gym_utils.async_vector_env import AsyncVectorEnv
  File "/home/lxc/movement-primitive-diffusion/movement_primitive_diffusion/utils/gym_utils/async_vector_env.py", line 37, in <module>
    from movement_primitive_diffusion.utils.gym_utils.vector_env import VectorEnv
  File "/home/lxc/movement-primitive-diffusion/movement_primitive_diffusion/utils/gym_utils/vector_env.py", line 11, in <module>
    from gymnasium.vector.utils.spaces import batch_space
ModuleNotFoundError: No module named 'gymnasium.vector.utils.spaces'`

**Comment by ScheiklP** [comment]
Hi @lidaken ,
Thanks for raising the issue!

I have updated the correct import path in this commit e378d873bda16471080e721d026c5e672d055485 .
Could you update your local repo and try again?

Best,
Paul

**Comment by lidaken** [comment]
> Hi @lidaken , Thanks for raising the issue!
> 
> I have updated the correct import path in this commit [e378d87](https://github.com/ScheiklP/movement-primitive-diffusion/commit/e378d873bda16471080e721d026c5e672d055485) . Could you update your local repo and try again?
> 
> Best, Paul

Hi Paul, Thanks for your help!
I update the local repo and try again, and the problem is solved. But a new error appear
`File "/home/lxc/movement-primitive-diffusion/movement_primitive_diffusion/utils/video.py", line 4, in <module>
    from moviepy.video.fx.resize import resize
ModuleNotFoundError: No module named 'moviepy.video.fx.resize'
I'm already install the moviepy and I find the function in moviepy documentation, but why this error appear
![image](https://github.com/user-attachments/assets/2776a2d0-eaa5-498b-9c87-41ab4dd57867)
Thanks a lot, daken

**Comment by ScheiklP** [comment]
Hi @lidaken 
did you checkout the most recent commit on main? In addition to the gymanisum fix, I pushed the fix for moviepy and another missing dependency.

Best,
Paul

**Comment by lidaken** [comment]
> Hi [@lidaken](https://github.com/lidaken) did you checkout the most recent commit on main? In addition to the gymanisum fix, I pushed the fix for moviepy and another missing dependency.
> 
> Best, Paul

Hi Paul, you are right. I update the new and it is ok now. And I'm sorry to reply you so late, you are so kind.
Thanks a lot, daken

**Comment by ScheiklP** [comment]
> > Hi [@lidaken](https://github.com/lidaken) did you checkout the most recent commit on main? In addition to the gymanisum fix, I pushed the fix for moviepy and another missing dependency.
> > 
> > Best, Paul
> 
> Hi Paul, you are right. I update the new and it is ok now. And I'm sorry to reply you so late, you are so kind.
> Thanks a lot, daken

No worries, happy I could help! :)
